FROM node:8

LABEL maintainer="William Le <william.le@passcareer.io>"

RUN apt-get update \
 && apt-get install -yyq ca-certificates libappindicator1 libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 gconf-service lsb-release wget xdg-utils fonts-liberation
RUN curl -L --fail https://github.com/docker/compose/releases/download/1.23.1/run.sh -o /usr/local/bin/docker-compose \
 && chmod +x /usr/local/bin/docker-compose
RUN yarn global add bower

# create app directory
RUN mkdir -p /usr/src/passcareer/linkedbooster.app-2
WORKDIR /usr/src/passcareer/linkedbooster.app-2

# install dependencies
COPY package.json yarn.lock ./
RUN yarn

COPY . ./
RUN bower install --allow-root
RUN ./node_modules/.bin/gulp production:vendors:compile
CMD [ "yarn", "test", "--forceExit" ]
