<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Kim Khi website</title>
  <meta content="" name="description">
  <meta content="Linked Booster" property="og:title">
  <meta content="" property="og:description">
  <meta content="width=device-width, initial-scale=1" name="viewport">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
</head>
<body class="layout-base {% block bodyClass %}{% endblock %}">
{% block main %}{% endblock %}
</body>
</html>
